name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: |
        python lzss3_setup.py build
    - if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ runner.os }}-lzss
        path: ${{ github.workspace }}/build
    - if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ runner.os }}-lzss
        path: ${{ github.workspace }}/build/exe.win-amd64-3.9
    - run: |
        python compress_setup.py build
    - if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ runner.os }}-compress
        path: ${{ github.workspace }}/build
    - if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ runner.os }}-compress
        path: ${{ github.workspace }}/build/exe.win-amd64-3.9
        
  Publish:
    needs: Build
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir publish
          cd publish
          mkdir linux
          cd linux
          mkdir compress
          mkdir lzss
          cd ../
          mkdir windows
          cd windows
          mkdir compress
          mkdir lzss
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Linux-compress
          path: ${{ github.workspace }}/publish/linux/compress
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Windows-compress
          path: ${{ github.workspace }}/publish/windows/compress
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Linux-lzss
          path: ${{ github.workspace }}/publish/linux/lzss
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Windows-lzss
          path: ${{ github.workspace }}/publish/windows/lzss
      - shell: cmd
        run: |
          pushd ${{ github.workspace }}
          cd publish
          7z a "${{ github.workspace }}/nlzss.zip" *.* -r
          popd
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Auto"
          prerelease: true
          title: "Auto Build"
          files: |
            *.zip
