name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - if: runner.os == 'Linux'
      run: |
        python lzss3_setup.py build
        mkdir lzss3
        mv -v exe.linux-x86_64-3.9/* lzss3/
        python compress_setup.py build
        mkdir compress
        mv -v exe.linux-x86_64-3.9/* compress/
    - if: runner.os == 'Windows'
      shell: cmd
      run : |
        python lzss3_setup.py build
        mkdir lzss3
        mv -v exe.win-amd64-3.9/* lzss3/
        python compress_setup.py build
        mkdir compress
        mv -v exe.win-amd64-3.9/* compress/
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ runner.os }}-build-lzss3
        path: ${{ github.workspace }}/build
        
  Publish:
    needs: Build
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: mkdir publish
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Linux-build
          path: ${{ github.workspace }}/publish
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Windows-build
          path: ${{ github.workspace }}/publish
      - shell: cmd
        run: |
          pushd ${{ github.workspace }}
          cd publish
          7z a "${{ github.workspace }}/nlzss.zip" *.* -r
          popd
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Auto"
          prerelease: true
          title: "Auto Build"
          files: |
            *.zip
